config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "/about", to: "pages#about"
  get "/team", to: "pages#team"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
  resources :itineraries, only: [:index, :new, :create, :show, :destroy] do
    resources :activities, only: [:index, :new, :create, :destroy]
    resources :itinerary_notes, only: [:new, :create, :destroy]
  end
  resources :itinerary_activity_joins, only: [:index, :show, :destroy] do
    resources :activity_notes, only: [:new, :create]
  end
  resources :activity_notes, only: [:edit, :update, :destroy]
  resources :users, only: [:show, :update, :index]
end

app/models/itinerary.rb
class Itinerary < ApplicationRecord
  include PgSearch::Model
  belongs_to :user
  has_many :itinerary_activity_joins, dependent: :destroy
  has_many :activities, through: :itinerary_activity_joins
  has_many :itinerary_notes, dependent: :destroy
  has_many_attached :photos
  pg_search_scope :search_name, against: [:name, :description, :location],
  using: {
    tsearch: { prefix: true }
  }
  # validates :start_date, presence: true
  # validates :end_date, presence: true
  validates :name, presence: true
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
end

app/controllers/itineraries_controller.rb
class ItinerariesController < ApplicationController
  before_action :set_itinerary, only: [:show, :destroy]

  def index
    @itineraries = policy_scope(current_user.itineraries)
    # @itineraries = Itinerary.all

    @markers = @itineraries.geocoded.map do |itinerary|
      {
        lat: itinerary.latitude,
        lng: itinerary.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: { itinerary: itinerary }),
        marker_html: render_to_string(partial: "marker")
      }
    end
  end

  def new

    @itinerary = Itinerary.new
    authorize @itinerary
    @no_records = session[:no_records]
    session[:no_records] = nil
  end


  # to be fixed so it can use strong params!!!
  def create
    # @itineraries = Itinerary.all

    @itinerary = Itinerary.new(itinerary_params)

    # @itinerary = Itinerary.new(name: params[:name], user: current_user)
    @itinerary.user = current_user
    @itinerary.name = params[:name]
    authorize @itinerary

    @activities = []

    # if(params[:name].present? && params[:category].present?)
    # @activities = Activity.where(location: params[:name].capitalize).where(category: params[:category])
    # else
    #   @activities = Activity.where(location: params[:name])
    # end
    @itinerary.location = params[:name]

    if !params[:name].empty? && !params[:category].nil?
      @activities = Activity.where("location ILIKE ?", "%#{params[:name]}%").where(category: params[:category])
      # @activities = Activity.where("location ILIKE '%#{params[:name]}%' AND category ILIKE '%#{params[:category]}%'")
      # @activities = Activity.where(location: params[:name], category: params[:category])
    elsif !params[:name].empty? && params[:category].nil?
      @activities = Activity.where(location: params[:name])
    elsif !params[:category].nil? && params[:name].empty?
      @activities = Activity.where(category: params[:category])
    end

    if @activities.empty?
      session[:no_records] = "Destination not available. Please input a different destination."
      return redirect_to new_itinerary_path
    end
    if @itinerary.save
      @activities.each { |activity| ItineraryActivityJoin.create!(itinerary: @itinerary, activity: activity) }
      # ItineraryActivityJoin.create!(itinerary: @itinerary, activity: @activity)
      return redirect_to itinerary_path(@itinerary)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    authorize @itinerary
    @itinerary_note = ItineraryNote.new(itinerary:@itinerary, user:current_user)
  end

  def destroy
    authorize @itinerary
    @itinerary.destroy
    redirect_to itinerary_path
  end

  private

  def set_itinerary
    @itinerary = Itinerary.find(params[:id])
  end

  def itinerary_params
    params.require(:itinerary).permit(:name, :start_date, :end_date, :location, photos: [])
  end
end

app/views/itineraries/_info_window.html.erb
<h2><%= itinerary.name %></h2>
<p><%= itinerary.location %></p>

app/views/itineraries/_itinerary_card.html.erb
<%= link_to  itinerary_path(itinerary), class:"link" do %>
    <div class="card mb-4 card-itinerary">
      <div class="card-body-itinerary d-flex justify-content-between shadow-lg p-3 mb-5 bg-white rounded" style="background-image:url(<%= asset_path 'ticket.jpg' %>);">
        <div class= "info" >
          <h5> <%= itinerary.name %> </h5>
          <p> <strong> Start Date: </strong>  <%= itinerary.start_date&.strftime("%d-%m-%Y") %> </p>
          <p> <strong> End Date: </strong>   <%= itinerary.end_date&.strftime("%d-%m-%Y") %> </p>
        </div>
        <div>
          <%= link_to itinerary_path(itinerary), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-delete custom-button" do %>
            <i class="fa fa-trash-o"></i>
          <% end %>
        </div>
      </div>
    </div>
<% end %>

app/views/itineraries/_marker.html.erb
<i class="fa fa-map-marker" aria-hidden="true" style="font-size:35px; color:#1C7C54"></i>

app/views/itineraries/index.html.erb
<div data-controller="scroll-top">
<div class="index">






    <div class="container pt-5 container-itinerary">
      <div class="title">
        <h1>MY TRAVEL ITINERARIES</h1>
        <i class="fa-solid fa-plane fa-3x fa-rotate-270"></i>
      </div>
      <div class="mb-3">
      <%= link_to "Create a new itinerary", new_itinerary_path, class: "btn btn-flat custom-button"%>
      </div>
          <% current_user.itineraries.each do |itinerary|  %>
          <%= render "itinerary_card", itinerary: itinerary %>
          <% end  %>
    </div>

    <div class="container pt-5">
      <div style="width: 100%; height: 600px;"
        data-controller="map"
        data-map-markers-value="<%= @markers.to_json %>"
        data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>




    <%= image_tag("stamp.png",
          width: 400, height: 300, crop: :fill) %>

    <div class="scroll-top">
      <button data-action="click->scroll-top#scrollToTop" class="scroll-top-button">
      <i class="fa fa-chevron-up"></i>
      </button>
    </div>



</div>
</div>

app/views/itineraries/new.html.erb
<div class="background">
  <div class="centering-text">
    <div class="transition-fade" data-controller="swup" id="swup">
      <h2>Give us some info and we will give you a customized trip</h2>
      <div class="container mt-3">
        <h5>Destination</h5>
        <%= form_with url: itineraries_path, method: :post, class: "d-flex flex-column", data: { controller: "flatpickr" } do |f| %>
          <div class="mb-5 form-control-destination cursor">
            <%= f.text_field :name,
              class: "search-input",
              placeholder: "Where do you want to go?"
            %>
            <i class="fa-solid fa-magnifying-glass text-dark"></i>
              <div class="mb-3">
                </div>
          </div>
          <h5>What kind of activities do you want to do? Select all that apply</h5>
          <div class="mb-3 d-flex flex-wrap justify-content-center">
            <%= f.collection_check_boxes :category,
              ["Day Trip", "Entry Ticket", "Guided Tour", "Hop-on hop-off tour", "Water Activity", "Workshop or Class"],
              :to_s,
              :to_s,
              include_hidden: false do |b| %>
              <div class="custom-checkbox me-3">
                <%= b.check_box %>
                <%= b.label %>
              </div>
            <% end %>
          </div>
          <%= f.simple_fields_for :itinerary, data: { controller: "flatpickr" } do |a| %>
             <div class="mb-3  cursor flatpickr-input calendar-form">

                 <%= a.input :start_date, as: :string, label:"Choose a start date", label_html: { style: "font-weight: bold;" } , input_html: { data: { flatpickr_target: "startTime" } }, class: " search-input"%>
                 <i class="fa-solid fa-calendar text-dark calendar"></i>

            </div>

            <div class="mb-3 cursor flatpickr-input calendar-form">
              <%= a.input :end_date, as: :string, label:"Choose an end date", label_html: { style: "font-weight: bold;" }, input_html: { data: { flatpickr_target: "endTime" } }, class: "search-input" %>
                <i class="fa-solid fa-calendar text-dark calendar"></i>
            </div>
          <% end %>
          <div class="container mt-3">
            <%= submit_tag "Search", class: "btn btn-flat custom-button ms-2" %>
          </div>

          <% if @no_records %>
            <%= @no_records %>
          <% end %>

        <% end %>
      </div>
    </div>
  </div>
</div>

  <%#= link_to "My Dashboard", itineraries_path, class: "btn btn-primary" %>

  <%#= form_with url: test_search_path, method: :get, class: "d-flex" do %>
    <%#= text_field_tag :search,
      params[:search],
      class: "form-control",
      placeholder: "Search for a itinerary"%>

    <%#= submit_tag "Search", class: "btn btn-flat ms-2" %>
  <%# end %>

app/views/itineraries/show.html.erb
<div class="itinerary">
  <div class="banner" style=" background-image: linear-gradient(rgba(0, 0, 0, 0.4), rgba(0, 0, 0, 0.4)), url('<%= @itinerary.itinerary_activity_joins.first.activity.banner %>');">
   <div class="container">
    <h1>
      My itinerary in <%= @itinerary.itinerary_activity_joins.first.activity.location %>
    </h1>
    <p>Start date: <%= @itinerary.start_date&.strftime("%d-%m-%Y") %></p>
    <p>End date: <%= @itinerary.end_date&.strftime("%d-%m-%Y") %></p>
   </div>
  </div>
  <div class="container">
    <% if !@itinerary.itinerary_activity_joins.empty? %>
      <div class="activities mb-5">
        <% @itinerary.itinerary_activity_joins.each do |join| %>
          <div class="card" style="width: 18rem">
            <%= image_tag join.activity.photo %>
            <div class="card-body">
              <p style="text-decoration: underline">
                <strong><%= join.activity.category %></strong>
              </p>
              <p><%= join.activity.Title %></p>
              <p>From <%= join.activity.price.to_i %>€ per person</p>
              <div class="d-flex justify-content-between">
                <div class="btn btn-flat custom-button" data-bs-toggle="modal" data-bs-target="#exampleModal<%= join.id %>">
                  <i class="fa fa-info" aria-hidden="true"></i>
                </div>
                <%= link_to join, data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-delete custom-button" do %>
                  <i class="fa fa-trash-o"></i>
                <% end %>
              </div>
            </div>
          </div>
          <div class="modal fade" id="exampleModal<%= join.id %>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLabel">
                    <strong><%= join.activity.Title %></strong>
                  </h5>
                  <button
                    type="button"
                    class="btn-close"
                    data-bs-dismiss="modal"
                    aria-label="Close"
                  ></button>
                </div>
                <div class="modal-body">
                  <div class="picture"><%= image_tag join.activity.photo %></div>
                  <p style="text-decoration: underline">
                    <%= join.activity.category %>
                  </p>
                  <p><%= join.activity.description %></p>
                  <p><strong>Address:</strong> <%= join.activity.address %></p>
                  <p>
                    <strong>Duration:</strong> <%= join.activity.duration %>
                    hour(s)
                  </p>
                  <p>
                    <strong>From</strong> €<%= join.activity.price.to_i %> per
                    person
                  </p>
                  <p>
                    Want more info or to book this? <%= link_to "Check it out
                    here!", join.activity.link, target: "_blank" %>
                  </p>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
  <div class="my-5 px-5 pt-5 border-top w-100">
    <h2 class="mb-2">Notes to self:</h2>
    <ul class="mb-4">
      <% @itinerary.itinerary_notes.each do |note| %>
        <li>
          <%= note.description %>
          <%= link_to itinerary_itinerary_note_path(@itinerary, note), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
            <i class="fa fa-trash-o"></i>
          <% end %>
        </li>
      <% end %>
    </ul>
    <%= simple_form_for [@itinerary, @itinerary_note] do |form| %>
      <%= form.input :description, label: false, placeholder: "Add a note about this itinerary", class: "search-input"%>
      <%= form.submit "Save", class: "btn btn-primary mt-2" %>
    <% end%>
  </div>
</div>