config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "/about", to: "pages#about"
  get "/team", to: "pages#team"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
  resources :itineraries, only: [:index, :new, :create, :show, :destroy] do
    resources :activities, only: [:index, :new, :create, :destroy]
    resources :itinerary_notes, only: [:new, :create, :destroy]
  end
  resources :itinerary_activity_joins, only: [:index, :show, :destroy] do
    resources :activity_notes, only: [:new, :create]
  end
  resources :activity_notes, only: [:edit, :update, :destroy]
  resources :users, only: [:show, :update, :index]
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <ul class="footer-links">
    <li><a href="/itineraries">Home</a></li>
    <li><a href="/about">About</a></li>
    <li><a href="/team">Team</a></li>
    <li><a href="/itineraries">Itineraries</a></li>
  </ul>
  <p>©2023 Le Wagon Schedulazy | All Rights Reserved</p>
</footer>

app/views/shared/_navbar.html.erb
<% unless current_page?(new_user_session_path) || current_page?(new_user_registration_path) %>
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon <%= "hidden" if current_page?(root_path) %>">
    <div class="container-fluid">
      <%= link_to new_itinerary_path, class: "navbar-brand" do %>
      <%= image_tag "logo.png", class:"logo"%>
        <%# <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
      <% end %>


      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto">
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to "New Itinerary", new_itinerary_path, class: "nav-link-word" %>
            </li>
            <li class="nav-item">
              <%= link_to "About Us", about_path, class: "nav-link-word" %>
            </li>
            <li class="nav-item dropdown">
              <% if current_user.photo.attached? %>
                <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false, style: "cursor: pointer" %>
              <% else %>
                <%= image_tag "icons8-user-30.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false, style: "cursor: pointer" %>
              <% end %>
              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <%= link_to "My profile", user_path(current_user), class: "dropdown-item" %>
                <%= link_to "My Itineraries", itineraries_path, class: "dropdown-item" %>
                <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
              </div>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Login", new_user_session_path, class: "nav-link" %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
<% end %>